import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Rommie Finder</title>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <div className="min-h-screen flex flex-col">
            <div className="bg-blue-200 text-black h-20 p-4 flex items-center">
              <h3>Roomie Finder</h3>
            </div>
            {children}
          </div>
          
        </MantineProvider>
      </body>
    </html>
  );
}
